frameworkVersion: ^3.38.0

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256

functions:
  main:
    handler: dist/index.default
    events:
      - httpApi: '*'
    environment:
      PLUGIN_SERVER_URL: http://localhost:4201
      API_KEY: 123456
      HOSTING_MODE: AWS_LAMBDA
