service: plugin1

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  memorySize: 256

functions:
  catchAllAny:
    handler: dist/index.default
    events:
      - httpApi: '*'
    environment:
      PLUGIN_SERVER_URL: http://localhost:4201
      API_KEY: 123456
      HOSTING_MODE: AWS_LAMBDA
