name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: connery-io/deploy-plugin-on-aws-lambda/build-and-deploy@v0.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          backend-config: backend_v3.hcl
