name: Deploy to Vercel

on:
  push:
    branches:
      - con-72

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install vercel -g

      - name: Deploy project artifacts to Vercel
        run: vercel deploy --yes --prod --token=${{ secrets.VERCEL_TOKEN }}
