name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SCOPE: connery

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install project dependencies
        run: npm install

      - name: Build project artifacts
        run: npm run build

      - name: Install Vercel CLI
        run: npm install vercel -g

      - name: Deploy project artifacts to Vercel
        run: vercel deploy --yes --prod --scope ${{env.SCOPE}} --token=${{ secrets.VERCEL_TOKEN }}
