name: Deploy to Vercel

on:
  push:
    branches:
      - con-72

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install vercel -g

      - name: Install project dependencies
        run: npm install

      - name: Build project artifacts
        run: npm run build

      - name: Deploy project artifacts to Vercel
        run: vercel deploy --yes --prod --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt

      - name: Keep the PLUGIN_SERVER_URL updated with the actual deployment URL
        run: vercel env add --prod PLUGIN_SERVER_URL < deployment-url.txt
